// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/ticketing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingRequest) Reset() {
	*x = BookingRequest{}
	mi := &file_pb_ticketing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRequest) ProtoMessage() {}

func (x *BookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ticketing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRequest.ProtoReflect.Descriptor instead.
func (*BookingRequest) Descriptor() ([]byte, []int) {
	return file_pb_ticketing_proto_rawDescGZIP(), []int{0}
}

func (x *BookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookingRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BookingRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_pb_ticketing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ticketing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_pb_ticketing_proto_rawDescGZIP(), []int{1}
}

func (x *BookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_pb_ticketing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ticketing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_pb_ticketing_proto_rawDescGZIP(), []int{2}
}

func (x *EventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type StockUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RemainingStock int32                  `protobuf:"varint,1,opt,name=remaining_stock,json=remainingStock,proto3" json:"remaining_stock,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StockUpdate) Reset() {
	*x = StockUpdate{}
	mi := &file_pb_ticketing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdate) ProtoMessage() {}

func (x *StockUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ticketing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdate.ProtoReflect.Descriptor instead.
func (*StockUpdate) Descriptor() ([]byte, []int) {
	return file_pb_ticketing_proto_rawDescGZIP(), []int{3}
}

func (x *StockUpdate) GetRemainingStock() int32 {
	if x != nil {
		return x.RemainingStock
	}
	return 0
}

func (x *StockUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueueStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatus) Reset() {
	*x = QueueStatus{}
	mi := &file_pb_ticketing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatus) ProtoMessage() {}

func (x *QueueStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ticketing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatus.ProtoReflect.Descriptor instead.
func (*QueueStatus) Descriptor() ([]byte, []int) {
	return file_pb_ticketing_proto_rawDescGZIP(), []int{4}
}

func (x *QueueStatus) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *QueueStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueueUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Position       int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueueUpdate) Reset() {
	*x = QueueUpdate{}
	mi := &file_pb_ticketing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdate) ProtoMessage() {}

func (x *QueueUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ticketing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdate.ProtoReflect.Descriptor instead.
func (*QueueUpdate) Descriptor() ([]byte, []int) {
	return file_pb_ticketing_proto_rawDescGZIP(), []int{5}
}

func (x *QueueUpdate) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *QueueUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueueUpdate) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

var File_pb_ticketing_proto protoreflect.FileDescriptor

const file_pb_ticketing_proto_rawDesc = "" +
	"\n" +
	"\x12pb/ticketing.proto\x12\tticketing\"`\n" +
	"\x0eBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"d\n" +
	"\x0fBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\")\n" +
	"\fEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"N\n" +
	"\vStockUpdate\x12'\n" +
	"\x0fremaining_stock\x18\x01 \x01(\x05R\x0eremainingStock\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"D\n" +
	"\vQueueStatus\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"l\n" +
	"\vQueueUpdate\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds2U\n" +
	"\x0eCatalogService\x12C\n" +
	"\x0eWatchLiveStock\x12\x17.ticketing.EventRequest\x1a\x16.ticketing.StockUpdate0\x012U\n" +
	"\x0eBookingService\x12C\n" +
	"\n" +
	"BookTicket\x12\x19.ticketing.BookingRequest\x1a\x1a.ticketing.BookingResponse2V\n" +
	"\fQueueService\x12F\n" +
	"\x10JoinPaymentQueue\x12\x16.ticketing.QueueStatus\x1a\x16.ticketing.QueueUpdate(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_pb_ticketing_proto_rawDescOnce sync.Once
	file_pb_ticketing_proto_rawDescData []byte
)

func file_pb_ticketing_proto_rawDescGZIP() []byte {
	file_pb_ticketing_proto_rawDescOnce.Do(func() {
		file_pb_ticketing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_ticketing_proto_rawDesc), len(file_pb_ticketing_proto_rawDesc)))
	})
	return file_pb_ticketing_proto_rawDescData
}

var file_pb_ticketing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_ticketing_proto_goTypes = []any{
	(*BookingRequest)(nil),  // 0: ticketing.BookingRequest
	(*BookingResponse)(nil), // 1: ticketing.BookingResponse
	(*EventRequest)(nil),    // 2: ticketing.EventRequest
	(*StockUpdate)(nil),     // 3: ticketing.StockUpdate
	(*QueueStatus)(nil),     // 4: ticketing.QueueStatus
	(*QueueUpdate)(nil),     // 5: ticketing.QueueUpdate
}
var file_pb_ticketing_proto_depIdxs = []int32{
	2, // 0: ticketing.CatalogService.WatchLiveStock:input_type -> ticketing.EventRequest
	0, // 1: ticketing.BookingService.BookTicket:input_type -> ticketing.BookingRequest
	4, // 2: ticketing.QueueService.JoinPaymentQueue:input_type -> ticketing.QueueStatus
	3, // 3: ticketing.CatalogService.WatchLiveStock:output_type -> ticketing.StockUpdate
	1, // 4: ticketing.BookingService.BookTicket:output_type -> ticketing.BookingResponse
	5, // 5: ticketing.QueueService.JoinPaymentQueue:output_type -> ticketing.QueueUpdate
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_ticketing_proto_init() }
func file_pb_ticketing_proto_init() {
	if File_pb_ticketing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_ticketing_proto_rawDesc), len(file_pb_ticketing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pb_ticketing_proto_goTypes,
		DependencyIndexes: file_pb_ticketing_proto_depIdxs,
		MessageInfos:      file_pb_ticketing_proto_msgTypes,
	}.Build()
	File_pb_ticketing_proto = out.File
	file_pb_ticketing_proto_goTypes = nil
	file_pb_ticketing_proto_depIdxs = nil
}
